# Generated by Django 4.2.4 on 2023-09-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameName', models.CharField(max_length=255)),
                ('lastRun', models.DateTimeField(blank=True, null=True)),
                ('countRun', models.IntegerField(blank=True, null=True)),
                ('gamePath', models.CharField(blank=True, max_length=255, null=True)),
                ('icoPath', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
