# Generated by Django 2.2.12 on 2023-10-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastTotalWin',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
