# Generated by Django 4.2.4 on 2023-09-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamePathDemo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
