# Generated by Django 2.2.12 on 2023-10-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_lasttotalwin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freeSpinCount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
