# Generated by Django 2.2.12 on 2023-10-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_freespincount'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='stonks',
            field=models.FloatField(default=0.0, max_length=10),
        ),
    ]
