# Generated by Django 4.2.4 on 2023-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icoPath',
            field=models.ImageField(upload_to='media/gameImg_images/'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='path_to_img',
            field=models.ImageField(upload_to='media/stock_images/'),
        ),
    ]
