# Generated by Django 4.2.4 on 2023-09-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_payment_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
