# Generated by Django 2.2.12 on 2023-10-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_referral_stonks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PerRef', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент прибыли с рефералов')),
                ('PerReturn', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Общий процент отдачи')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
