# Generated by Django 4.2.4 on 2023-09-11 07:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatars/1s.png', upload_to='avatars/'),
        ),
    ]
