# Generated by Django 4.2.4 on 2023-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Статус 1'), (2, 'Статус 2'), (3, 'Статус 3'), (4, 'Статус 4'), (5, 'Статус 5')], default=1),
        ),
    ]
