# Generated by Django 4.2.4 on 2023-10-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProfitBal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CyclBal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
