# Generated by Django 4.2.4 on 2023-09-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='f06651a1f0', max_length=10, unique=True),
        ),
    ]
