# Generated by Django 4.2.4 on 2023-10-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='CyclBal',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='balance',
            name='ProfitBal',
            field=models.FloatField(max_length=10),
        ),
    ]
