# Generated by Django 2.2.12 on 2023-10-30 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dailydeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydeposit',
            name='deposit_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
