# Generated by Django 4.2.4 on 2023-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_referral_code_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
